### PR TITLE
Feat/c search notes

### PR DESCRIPTION
**Pull request by kritgrover**
## Describe your changes
Added searchNote, insertDate

## Checklist before requesting a review
a) Type of change
  - [ ] Bug fix
  - [ ] Documentation update
  - [x] Added feature
        
b) Self code review completed?
  - [x] Yes
  - [ ] No

### CODE REVIEW

**Comment by Yatin-Malhotra** [comment]
Krit sucks

**Comment by Vraj2004** [comment]
Krit goated

**Comment by rkwan05** [comment]
👍

**Review by rkwan05 — APPROVED** [review]

**Review by shamssab — COMMENTED** [review]
good

**Review by Yatin-Malhotra — APPROVED** [review]
code workey!!

**Review by Vraj2004 — APPROVED** [review]

**Pull request merged**
